name: aocl-win
on: workflow_dispatch
jobs:
  aocl-win:
    runs-on: windows-2022
    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          repository: amd/aocl
      - name: GCC
        run: |
          C:/msys64/usr/bin/wget.exe -q https://github.com/brechtsanders/winlibs_mingw/releases/download/13.3.0posix-11.0.1-ucrt-r1/winlibs-x86_64-posix-seh-gcc-13.3.0-mingw-w64ucrt-11.0.1-r1.7z
          7z x winlibs-x86_64-posix-seh-gcc-13.3.0-mingw-w64ucrt-11.0.1-r1.7z
      - name: Compile
        shell: bash
        run: |
          find . -name '*.cmake' -exec sed -i 's/--target install -j/--target install/' {} +
          find . -name '*.cmake' -exec sed -i 's/--config ${CMAKE_BUILD_TYPE} -j/--config ${CMAKE_BUILD_TYPE}/' {} +
          cmake --preset aocl-win-ninja-lp-ga-config \
          -G "MinGW Makefiles" \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_C_COMPILER=D:/a/prebuilds/prebuilds/mingw64/bin/gcc.exe \
          -DCMAKE_CXX_COMPILER=D:/a/prebuilds/prebuilds/mingw64/bin/g++.exe \
          -DCMAKE_Fortran_COMPILER=D:/a/prebuilds/prebuilds/mingw64/bin/gfortran.exe \
          -DBUILD_SHARED_LIBS=OFF \
          -DENABLE_CBLAS=OFF \
          -DENABLE_AOCL_COMPRESSION=OFF \
          -DENABLE_AOCL_CRYPTO=OFF \
          -DCMAKE_INSTALL_PREFIX=aocl-install \
          -DOpenMP_libomp_LIBRARY="" \
          --fresh
          cmake --build build --config Release --target install --parallel
          cd aocl-install && 7z a ../aocl-win-gcc.7z .
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: aocl-win-gcc.7z
          asset_name: aocl-win-gcc.7z
          tag: latest
          overwrite: true
