name: caliper
on: workflow_dispatch
env:
  ARCHIVE: ''
jobs:
  caliper:
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: MKL
        run: |
          wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update && sudo apt-get install intel-oneapi-mpi-devel intel-oneapi-mpi
      - name: Compile
        run: |
          source /opt/intel/oneapi/setvars.sh
          git clone --depth 1 --branch v2.12.1 https://github.com/LLNL/Caliper.git
          export ARCHIVE=caliper-linux.7z
          echo "ARCHIVE=$ARCHIVE" >> "$GITHUB_ENV"
          mkdir install && mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DWITH_MPI=ON -DWITH_TAU=ON -DWITH_VTUNE=ON -DCMAKE_INSTALL_PREFIX=../install ../Caliper
          cmake --build . --target install --config Release --parallel 4
          cd ../install/ && 7z a ../$ARCHIVE .
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.ARCHIVE }}
          asset_name: ${{ env.ARCHIVE }}
          tag: latest
          overwrite: true
