name: hdf5-linux
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  hdf5-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Compile
        run: |
          wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.14/hdf5-1.14.3/src/CMake-hdf5-1.14.3.tar.gz
          tar xf CMake-hdf5-1.14.3.tar.gz
          cd CMake-hdf5-1.14.3
          ctest -S HDF5config.cmake,BUILD_GENERATOR=Unix -C Release -O hdf5.log
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: CMake-hdf5-1.14.3/HDF5-1.14.3-Linux.tar.gz
          asset_name: HDF5-1.14.3-Linux.tar.gz
          tag: latest
          overwrite: true