name: hdf5-win
on: workflow_dispatch
jobs:
  hdf5-win:
    runs-on: windows-2022
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Compile
        run: |
          C:/msys64/usr/bin/wget.exe -q https://support.hdfgroup.org/releases/hdf5/v1_14/v1_14_5/downloads/hdf5-1.14.5.zip
          unzip hdf5-1.14.5.zip
          cd hdf5-1.14.5
          ctest -S HDF5config.cmake,BUILD_GENERATOR=VS202264 -C Release -O hdf5.log
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: hdf5-1.14.5/HDF5-1.14.5-win64.zip
          asset_name: HDF5-1.14.5-win64.zip
          tag: latest
          overwrite: true