name: hdf5-win
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  hdf5-win-vs:
    runs-on: windows-2019
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Compile
        run: |
          C:/msys64/usr/bin/wget.exe https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.6/src/hdf5-1.10.6.zip
          unzip hdf5-1.10.6.zip && mkdir tmp && cd tmp
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../build ../hdf5-1.10.6
          cmake --build . --target INSTALL --config Release
          cd ../build
          7z a ../HDF5-1.10.6-win64-vs.7z ./*
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: HDF5-1.10.6-win64-vs.7z
          asset_name: HDF5-1.10.6-win64-vs.7z
          tag: latest
          overwrite: true
  hdf5-win-gcc:
    runs-on: windows-2019
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Compile
        run: |
          choco install mingw --version=10.3.0
          C:/msys64/usr/bin/wget.exe https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.6/src/hdf5-1.10.6.zip
          unzip hdf5-1.10.6.zip && mkdir tmp && cd tmp
          cmake -G "MinGW Makefiles"  -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=D:/a/prebuilds/prebuilds/build ../hdf5-1.10.6
          cmake --build . --target INSTALL --config Release
          cd ../build
          7z a ../HDF5-1.10.6-win64-gcc.7z ./*
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: HDF5-1.10.6-win64-gcc.7z
          asset_name: HDF5-1.10.6-win64-gcc.7z
          tag: latest
          overwrite: true