name: hdf5-win
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  hdf5-win:
    runs-on: windows-2019
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Compile
        run: |
          C:/msys64/usr/bin/wget.exe https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.14/hdf5-1.14.2/src/CMake-hdf5-1.14.2.zip
          unzip CMake-hdf5-1.14.2.zip
          cd CMake-hdf5-1.14.2
          ctest -S HDF5config.cmake,BUILD_GENERATOR=VS201964 -C Release -O hdf5.log
      - name: Debug
        if: failure()
        uses: mxschmitt/action-tmate@v3
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: CMake-hdf5-1.14.2/HDF5-1.14.2-win64.zip
          asset_name: HDF5-1.14.2-win64.zip
          tag: latest
          overwrite: true