name: hdf5-linux
on: workflow_dispatch
jobs:
  hdf5-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Compile
        run: |
          wget -q https://support.hdfgroup.org/releases/hdf5/v1_14/v1_14_5/downloads/hdf5-1.14.5.tar.gz
          tar xf hdf5-1.14.5.tar.gz
          cd hdf5-1.14.5
          ctest -S HDF5config.cmake,BUILD_GENERATOR=Unix -C Release -O hdf5.log
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: hdf5-1.14.5/HDF5-1.14.5-Linux.tar.gz
          asset_name: HDF5-1.14.5-Linux.tar.gz
          tag: latest
          overwrite: true