name: hdf5-win
on: workflow_dispatch
jobs:
  hdf5-win:
    runs-on: windows-2022
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Compile
        run: |
          C:/msys64/usr/bin/wget.exe -q https://support.hdfgroup.org/releases/hdf5/v1_14/v1_14_5/downloads/hdf5-1.14.5.zip && unzip hdf5-1.14.5.zip
          mkdir packing && mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DHDF5_ENABLE_Z_LIB_SUPPORT=OFF -DCMAKE_INSTALL_PREFIX=../packing ../hdf5-1.14.5
          cmake --build . --target install --config Release --parallel 4
          cd ../packing && 7z a ../HDF5-1.14.5-win.zip ./*
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: HDF5-1.14.5-win.zip
          asset_name: HDF5-1.14.5-win.zip
          tag: latest
          overwrite: true