name: hdf5-macos
on: workflow_dispatch
jobs:
  hdf5-macos:
    runs-on: macos-13
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Compile
        run: |
          export CC=gcc-11 && export CXX=g++-11 && export FC=gfortran-11
          wget -q https://support.hdfgroup.org/releases/hdf5/v1_14/v1_14_5/downloads/hdf5-1.14.5.tar.gz
          tar xf hdf5-1.14.5.tar.gz
          cd hdf5-1.14.5
          ctest -S HDF5config.cmake,BUILD_GENERATOR=Unix -C Release -O hdf5.log
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: hdf5-1.14.5/HDF5-1.14.5-Darwin.tar.gz
          asset_name: HDF5-1.14.5-Darwin.tar.gz
          tag: latest
          overwrite: true