name: mimalloc-macos
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  mimalloc-macos:
    runs-on: macos-13
    steps:
      - name: Compile
        run: |
          git clone --depth 1 https://github.com/microsoft/mimalloc.git
          mkdir mimalloc-macos && mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../mimalloc-macos ../mimalloc
          make install -j4
          cd ..
          tar cvzf mimalloc-macos.tar.gz ./mimalloc-macos/*
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: mimalloc-macos.tar.gz
          asset_name: mimalloc-macos.tar.gz
          tag: latest
          overwrite: true