name: mimalloc-win-gcc
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  mimalloc-win-gcc:
    runs-on: windows-2022
    steps:
      - name: Compile
        run: |
          choco install mingw --version=13.2.0
          git clone --depth 1 https://github.com/microsoft/mimalloc.git
          mkdir mimalloc-win-gcc && mkdir build && cd build
          cmake -G "MinGW Makefiles" -DCMAKE_C_COMPILER=C:/ProgramData/mingw64/mingw64/bin/gcc.exe -DCMAKE_CXX_COMPILER=C:/ProgramData/mingw64/mingw64/bin/g++.exe -DCMAKE_Fortran_COMPILER=C:/ProgramData/mingw64/mingw64/bin/gfortran.exe -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=D:/a/prebuilds/prebuilds/mimalloc-win-gcc ../mimalloc
          make install -j4
          cd ../mimalloc-win-gcc
          7z a ../mimalloc-win-gcc.7z ./*
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: mimalloc-win-gcc.7z
          asset_name: mimalloc-win-gcc.7z
          tag: latest
          overwrite: true