name: mimalloc-win-vs
on: workflow_dispatch
jobs:
  mimalloc-win-vs:
    runs-on: windows-2022
    steps:
      - name: Compile
        run: |
          git clone --depth 1 https://github.com/microsoft/mimalloc.git
          mkdir mimalloc-win-vs && mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=D:/a/prebuilds/prebuilds/mimalloc-win-vs ../mimalloc
          make install -j4
          cd ../mimalloc-win-vs
          7z a ../mimalloc-win-vs.7z ./*
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: mimalloc-win-vs.7z
          asset_name: mimalloc-win-vs.7z
          tag: latest
          overwrite: true