name: openblas-macos
on: workflow_dispatch
jobs:
  openblas-macos:
    runs-on: macos-13
    steps:
      - name: Compile
        run: |
          export CC=gcc-13 && export CXX=g++-13 && export FC=gfortran-13
          wget -q https://github.com/xianyi/OpenBLAS/releases/download/v0.3.28/OpenBLAS-0.3.28.tar.gz
          tar xf OpenBLAS-0.3.28.tar.gz && rm OpenBLAS-0.3.28.tar.gz && cd OpenBLAS-0.3.28
          sed -i '~' 's/# DYNAMIC_ARCH = 1/DYNAMIC_ARCH = 1/g' Makefile.rule
          sed -i '~' 's/# BINARY=64/BINARY=64/g' Makefile.rule
          sed -i '~' 's/# USE_THREAD = 0/USE_THREAD = 1/g' Makefile.rule
          sed -i '~' 's/# USE_OPENMP = 1/USE_OPENMP = 1/g' Makefile.rule
          sed -i '~' 's/# NUM_THREADS = 24/NUM_THREADS = 64/g' Makefile.rule
          sed -i '~' 's/# NO_CBLAS = 1/NO_CBLAS = 1/g' Makefile.rule
          sed -i '~' 's/# NO_LAPACKE = 1/NO_LAPACKE = 1/g' Makefile.rule
          sed -i '~' 's/# GEMM_MULTITHREAD_THRESHOLD = 4/GEMM_MULTITHREAD_THRESHOLD = 64/g' Makefile.rule
          make
          tar cvzf ../OpenBLAS-0.3.28-macos-and64.tar.gz lib*.*
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: OpenBLAS-0.3.28-macos-and64.tar.gz
          asset_name: OpenBLAS-0.3.28-macos-and64.tar.gz
          tag: latest
          overwrite: true
  openblas-macos-arm64:
    runs-on: macos-14
    steps:
      - name: Compile
        run: |
          export CC=gcc-13 && export CXX=g++-13 && export FC=gfortran-13
          wget -q https://github.com/xianyi/OpenBLAS/releases/download/v0.3.28/OpenBLAS-0.3.28.tar.gz
          tar xf OpenBLAS-0.3.28.tar.gz && rm OpenBLAS-0.3.28.tar.gz && cd OpenBLAS-0.3.28
          sed -i '~' 's/# DYNAMIC_ARCH = 1/DYNAMIC_ARCH = 1/g' Makefile.rule
          sed -i '~' 's/# BINARY=64/BINARY=64/g' Makefile.rule
          sed -i '~' 's/# USE_THREAD = 0/USE_THREAD = 1/g' Makefile.rule
          sed -i '~' 's/# USE_OPENMP = 1/USE_OPENMP = 1/g' Makefile.rule
          sed -i '~' 's/# NUM_THREADS = 24/NUM_THREADS = 64/g' Makefile.rule
          sed -i '~' 's/# NO_CBLAS = 1/NO_CBLAS = 1/g' Makefile.rule
          sed -i '~' 's/# NO_LAPACKE = 1/NO_LAPACKE = 1/g' Makefile.rule
          sed -i '~' 's/# GEMM_MULTITHREAD_THRESHOLD = 4/GEMM_MULTITHREAD_THRESHOLD = 64/g' Makefile.rule
          make
          tar cvzf ../OpenBLAS-0.3.28-macos-arm64.tar.gz lib*.*
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: OpenBLAS-0.3.28-macos-arm64.tar.gz
          asset_name: OpenBLAS-0.3.28-macos-arm64.tar.gz
          tag: latest
          overwrite: true
        