name: openblas-macos
on: workflow_dispatch
jobs:
  openblas-macos:
    strategy:
      matrix:
        os: [ macos-14-large, macos-15-large, macos-14-xlarge, macos-15-xlarge ]
        version: [ 0.3.30 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Compile
        run: |
          wget -q https://github.com/xianyi/OpenBLAS/releases/download/v${{ matrix.version }}/OpenBLAS-${{ matrix.version }}.tar.gz
          tar xf OpenBLAS-${{ matrix.version }}.tar.gz && rm OpenBLAS-${{ matrix.version }}.tar.gz && cd OpenBLAS-${{ matrix.version }}
          sed -i '~' 's/# DYNAMIC_ARCH = 1/DYNAMIC_ARCH = 1/g' Makefile.rule
          sed -i '~' 's/# BINARY=64/BINARY=64/g' Makefile.rule
          sed -i '~' 's/# USE_THREAD = 0/USE_THREAD = 1/g' Makefile.rule
          sed -i '~' 's/# USE_OPENMP = 1/USE_OPENMP = 1/g' Makefile.rule
          sed -i '~' 's/# NUM_THREADS = 24/NUM_THREADS = 64/g' Makefile.rule
          sed -i '~' 's/# NO_CBLAS = 1/NO_CBLAS = 1/g' Makefile.rule
          sed -i '~' 's/# NO_LAPACKE = 1/NO_LAPACKE = 1/g' Makefile.rule
          sed -i '~' 's/# GEMM_MULTITHREAD_THRESHOLD = 4/GEMM_MULTITHREAD_THRESHOLD = 64/g' Makefile.rule
          make CC=gcc-13 CXX=g++-13 FC=gfortran-13
          dyld_info -dependents libopenblas.dylib
          tar cvzf ../OpenBLAS-${{ matrix.version }}-${{ matrix.os }}.tar.gz lib*.*
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: OpenBLAS-${{ matrix.version }}-${{ matrix.os }}.tar.gz
          asset_name: OpenBLAS-${{ matrix.version }}-${{ matrix.os }}.tar.gz
          tag: latest
          overwrite: true
        