name: scalapack
on: workflow_dispatch
env:
  ARCHIVE: ''
jobs:
  scalapack:
    runs-on: ubuntu-22.04
    steps:
      - name: Compile
        run: |
          export ARCHIVE=scalapack-linux.tar.gz
          echo "ARCHIVE=$ARCHIVE" >> "$GITHUB_ENV"
          wget -q https://github.com/TLCFEM/prebuilds/releases/download/latest/openmpi-linux.tar.gz
          tar -xf openmpi-linux.tar.gz
          wget -q https://github.com/Reference-ScaLAPACK/scalapack/archive/refs/tags/v2.2.2.tar.gz
          tar -xf v2.2.2.tar.gz
          cd scalapack-2.2.2
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DMPI_HOME=../../openmpi-linux ..
          make -j
      - name: Debug
        uses: mxschmitt/action-tmate@v3
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.ARCHIVE }}
          asset_name: ${{ env.ARCHIVE }}
          tag: latest
          overwrite: true