name: tbb-linux
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  tbb-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Compile
        run: |
          git clone --depth 1 https://github.com/oneapi-src/oneTBB.git
          mkdir tbb-linux && mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DTBB_TEST=OFF -DCMAKE_INSTALL_PREFIX=../tbb-linux ../oneTBB
          make install -j4
          cd ..
          tar cvzf tbb-linux.tar.gz ./tbb-linux/*
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tbb-linux.tar.gz
          asset_name: tbb-linux.tar.gz
          tag: latest
          overwrite: true