name: tbb-macos
on: workflow_dispatch
jobs:
  tbb-macos:
    runs-on: macos-13
    steps:
      - name: Compile
        run: |
          export CC=$(brew --prefix llvm@15)/bin/clang && export CXX=$(brew --prefix llvm@15)/bin/clang++
          git clone --depth 1 --branch v2022.0.0 https://github.com/oneapi-src/oneTBB.git
          mkdir tbb-macos && mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DTBB_TEST=OFF -DCMAKE_INSTALL_PREFIX=../tbb-macos ../oneTBB
          make install -j4
          cd ..
          tar cvzf tbb-macos.tar.gz ./tbb-macos/*
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tbb-macos.tar.gz
          asset_name: tbb-macos.tar.gz
          tag: latest
          overwrite: true