name: tbb-win-gcc
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  tbb-win-gcc:
    runs-on: windows-2022
    steps:
      - name: Compile
        run: |
          choco install mingw --version=13.2.0
          git clone --depth 1 --branch v2021.12.0 https://github.com/oneapi-src/oneTBB.git
          C:/msys64/usr/bin/sed.exe -i 's@if (NOT APPLE)@if (NOT APPLE AND NOT MINGW)@g' oneTBB/cmake/compilers/GNU.cmake
          C:/msys64/usr/bin/sed.exe -i 's@-Werror=format-security@-Werror=format-security -Wno-error=unused-value@g' oneTBB/cmake/compilers/GNU.cmake
          mkdir build && cd build
          cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=C:/ProgramData/mingw64/mingw64/bin/gcc.exe -DCMAKE_CXX_COMPILER=C:/ProgramData/mingw64/mingw64/bin/g++.exe -DCMAKE_Fortran_COMPILER=C:/ProgramData/mingw64/mingw64/bin/gfortran.exe -DTBB_TEST=OFF -DCMAKE_INSTALL_PREFIX=D:/a/prebuilds/prebuilds/tbb-win-gcc ../oneTBB
          cmake --build . --target install --config Release --parallel 4
          cd ../tbb-win-gcc
          7z a ../tbb-win-gcc.7z ./*
      # - name: Debug
      #   if: failure()
      #   uses: mxschmitt/action-tmate@v3
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tbb-win-gcc.7z
          asset_name: tbb-win-gcc.7z
          tag: latest
          overwrite: true