name: tbb
on: workflow_dispatch
env:
  ARCHIVE: ''
jobs:
  tbb:
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-13 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure
        if: matrix.os == 'macos-13'
        run: |
          export CC=$(brew --prefix llvm@15)/bin/clang && export CXX=$(brew --prefix llvm@15)/bin/clang++
      - name: Compile
        run: |
          if [ ${{ matrix.os }} == 'ubuntu-22.04' ]; then
            echo "ARCHIVE=tbb-linux.7z" >> "$GITHUB_ENV"
          else
            brew install p7zip
            echo "ARCHIVE=tbb-macos.7z" >> "$GITHUB_ENV"
          fi
          git clone --depth 1 --branch v2022.0.0 https://github.com/oneapi-src/oneTBB.git
          mkdir tbb-install && mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DTBB_TEST=OFF -DCMAKE_INSTALL_PREFIX=../tbb-install ../oneTBB
          cmake --build . --target install --config Release --parallel 4
          cd .. && 7z a ${{ env.ARCHIVE }} tbb-install
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.ARCHIVE }}
          asset_name: ${{ env.ARCHIVE }}
          tag: latest
          overwrite: true
