name: tbb
on: workflow_dispatch
env:
  ARCHIVE: ''
jobs:
  tbb:
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-14-large, macos-15-large, macos-14-xlarge, macos-15-xlarge ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Compile
        run: |
          if [ ${{ matrix.os }} == 'ubuntu-22.04' ]; then
            export ARCHIVE=tbb-linux.tar.gz
          else
            if [[ "${{ matrix.os }}" == "macos-15-large" || "${{ matrix.os }}" == "macos-15-xlarge" ]]; then
              export CC=$(brew --prefix llvm@18)/bin/clang
              export CXX=$(brew --prefix llvm@18)/bin/clang++
            else
              export CC=$(brew --prefix llvm@15)/bin/clang
              export CXX=$(brew --prefix llvm@15)/bin/clang++
            fi
            export ARCHIVE=tbb-${{ matrix.os }}.tar.gz
          fi
          echo "ARCHIVE=$ARCHIVE" >> "$GITHUB_ENV"
          git clone --depth 1 --branch v2022.1.0 https://github.com/oneapi-src/oneTBB.git
          mkdir tbb-install && mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DTBB_TEST=OFF -DCMAKE_INSTALL_PREFIX=../tbb-install ../oneTBB
          cmake --build . --target install --config Release --parallel 4
          cd .. && tar czf $ARCHIVE tbb-install
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.ARCHIVE }}
          asset_name: ${{ env.ARCHIVE }}
          tag: latest
          overwrite: true
