name: v82-win
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  v82-win:
    runs-on: windows-2019
    steps:
      - name: Compile
        run: |
          C:/msys64/usr/bin/wget.exe https://www.vtk.org/files/release/8.2/VTK-8.2.0.tar.gz
          tar xf VTK-8.2.0.tar.gz && del VTK-8.2.0.tar.gz
          mkdir VTK-build && mkdir VTK-out && cd VTK-build
          cmake -DCMAKE_BUILD_TYPE=Release -DVTK_PYTHON_VERSON=3 -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=D:/a/prebuilds/prebuilds/VTK-out ../VTK-8.2.0
          cmake --build . --target INSTALL --config Release
          cd ../VTK-out
          7z a ../VTK-8.2.0-win.7z ./*
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: VTK-8.2.0-win.7z
          asset_name: VTK-8.2.0-win.7z
          tag: latest
          overwrite: true