name: vtk-win
on: workflow_dispatch
jobs:
  vtk-win:
    runs-on: windows-2022
    steps:
      - name: Compile
        run: |
          C:/msys64/usr/bin/wget.exe -q https://www.vtk.org/files/release/9.4/VTK-9.4.0.tar.gz
          tar xf VTK-9.4.0.tar.gz && del VTK-9.4.0.tar.gz
          mkdir VTK-build && mkdir VTK-out && cd VTK-build
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=D:/a/prebuilds/prebuilds/VTK-out ../VTK-9.4.0
          cmake --build . --target install --config Release --parallel 4
          cd ../VTK-out
          7z a ../VTK-9.4.0-win.7z ./*
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: VTK-9.4.0-win.7z
          asset_name: VTK-9.4.0-win.7z
          tag: latest
          overwrite: true