name: vtk-win-gcc
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  vtk-win-gcc:
    runs-on: windows-2022
    steps:
      - name: Compile
        run: |
          C:/msys64/usr/bin/wget.exe -q https://github.com/brechtsanders/winlibs_mingw/releases/download/13.2.0posix-18.1.5-11.0.1-msvcrt-r8/winlibs-x86_64-posix-seh-gcc-13.2.0-mingw-w64msvcrt-11.0.1-r8.7z
          7z x winlibs-x86_64-posix-seh-gcc-13.2.0-mingw-w64msvcrt-11.0.1-r8.7z
          C:/msys64/usr/bin/wget.exe -q https://www.vtk.org/files/release/9.3/VTK-9.3.1.tar.gz
          tar xf VTK-9.3.1.tar.gz && del VTK-9.3.1.tar.gz
          mkdir VTK-build && mkdir VTK-out && cd VTK-build
          cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=D:/a/prebuilds/prebuilds/mingw64/bin/gcc.exe -DCMAKE_CXX_COMPILER=D:/a/prebuilds/prebuilds/mingw64/bin/g++.exe -DCMAKE_Fortran_COMPILER=D:/a/prebuilds/prebuilds/mingw64/bin/gfortran.exe -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=D:/a/prebuilds/prebuilds/VTK-out ../VTK-9.3.1
          cmake --build . --target install --config Release --parallel 4
          cd ../VTK-out
          7z a ../VTK-9.3.1-win-gcc.7z ./*
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: VTK-9.3.1-win-gcc.7z
          asset_name: VTK-9.3.1-win-gcc.7z
          tag: latest
          overwrite: true