name: vtk-macos
on: workflow_dispatch
env:
  major: "9"
  minor: "5"
  patch: "2"
jobs:
  vtk-macos:
    strategy:
      matrix:
        os: [macos-14-large, macos-15-large, macos-14-xlarge, macos-15-xlarge]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Compile
        run: |
          export VERSION=${{ env.major }}.${{ env.minor }}.${{ env.patch }}
          export FC=gfortran-13
          brew install glfw glew
          wget -q https://www.vtk.org/files/release/${{ env.major }}.${{ env.minor }}/VTK-$VERSION.tar.gz
          tar xf VTK-$VERSION.tar.gz && rm VTK-$VERSION.tar.gz
          mkdir VTK-build && cd VTK-build
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=../VTK-out ../VTK-$VERSION
          cmake --build . --target install --config Release --parallel 4
          cd ../VTK-out
          tar cvzf ../VTK-$VERSION-${{ matrix.os }}.tar.gz ./*
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: VTK-${{ env.major }}.${{ env.minor }}.${{ env.patch }}-${{ matrix.os }}.tar.gz
          asset_name: VTK-${{ env.major }}.${{ env.minor }}.${{ env.patch }}-${{ matrix.os }}.tar.gz
          tag: latest
          overwrite: true
