name: vtk-macos
on: workflow_dispatch
env:
  major: "9"
  minor: "5"
  patch: "1"
jobs:
  vtk-macos:
    runs-on: macos-13
    steps:
      - name: Compile
        run: |
          export FC=gfortran-13
          brew install glfw glew
          wget -q https://www.vtk.org/files/release/${{ env.major }}.${{ env.minor }}/VTK-${{ env.major }}.${{ env.minor }}.${{ env.patch }}.tar.gz -O VTK.tar.gz
          tar xf VTK.tar.gz && rm VTK.tar.gz
          mkdir VTK-build && cd VTK-build
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=../VTK-out ../VTK
          cmake --build . --target install --config Release --parallel 4
          cd ../VTK-out
          tar cvzf ../VTK-${{ env.major }}.${{ env.minor }}.${{ env.patch }}-macos.tar.gz ./*
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: VTK-${{ env.major }}.${{ env.minor }}.${{ env.patch }}-macos.tar.gz
          asset_name: VTK-${{ env.major }}.${{ env.minor }}.${{ env.patch }}-macos.tar.gz
          tag: latest
          overwrite: true