name: vtk-win
on: workflow_dispatch
jobs:
  vtk-win-vs:
    runs-on: windows-2022
    steps:
      - name: Compile
        run: |
          C:/msys64/usr/bin/wget.exe -q https://www.vtk.org/files/release/9.4/VTK-9.4.1.tar.gz
          tar xf VTK-9.4.1.tar.gz && del VTK-9.4.1.tar.gz
          mkdir VTK-build && mkdir VTK-out && cd VTK-build
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=D:/a/prebuilds/prebuilds/VTK-out ../VTK-9.4.1
          cmake --build . --target install --config Release --parallel 4
          cd ../VTK-out
          7z a ../VTK-9.4.1-win.7z ./*
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: VTK-9.4.1-win.7z
          asset_name: VTK-9.4.1-win.7z
          tag: latest
          overwrite: true
  vtk-win-gcc:
    runs-on: windows-2022
    steps:
      - name: Compile
        run: |
          C:/msys64/usr/bin/wget.exe -q https://github.com/brechtsanders/winlibs_mingw/releases/download/13.3.0posix-11.0.1-ucrt-r1/winlibs-x86_64-posix-seh-gcc-13.3.0-mingw-w64ucrt-11.0.1-r1.7z
          7z x winlibs-x86_64-posix-seh-gcc-13.3.0-mingw-w64ucrt-11.0.1-r1.7z
          C:/msys64/usr/bin/wget.exe -q https://www.vtk.org/files/release/9.4/VTK-9.4.1.tar.gz
          tar xf VTK-9.4.1.tar.gz && del VTK-9.4.1.tar.gz
          mkdir VTK-build && mkdir VTK-out && cd VTK-build
          cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=D:/a/prebuilds/prebuilds/mingw64/bin/gcc.exe -DCMAKE_CXX_COMPILER=D:/a/prebuilds/prebuilds/mingw64/bin/g++.exe -DCMAKE_Fortran_COMPILER=D:/a/prebuilds/prebuilds/mingw64/bin/gfortran.exe -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=D:/a/prebuilds/prebuilds/VTK-out ../VTK-9.4.1
          cmake --build . --target install --config Release --parallel 4
          cd ../VTK-out
          7z a ../VTK-9.4.1-win-gcc.7z ./*
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: VTK-9.4.1-win-gcc.7z
          asset_name: VTK-9.4.1-win-gcc.7z
          tag: latest
          overwrite: true