name: v92-vtk-macos
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  v92-vtk-macos:
    runs-on: macos-11
    steps:
      - name: Compile
        run: |
          export FC=gfortran-11
          brew install glfw glew
          wget -q https://www.vtk.org/files/release/9.2/VTK-9.2.6.tar.gz
          tar xf VTK-9.2.6.tar.gz && rm VTK-9.2.6.tar.gz
          mkdir VTK-build && cd VTK-build
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=../VTK-out ../VTK-9.2.6
          make install -j4
          cd ../VTK-out
          tar cvzf ../VTK-9.2.6-macos.tar.gz ./*
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: VTK-9.2.6-macos.tar.gz
          asset_name: VTK-9.2.6-macos.tar.gz
          tag: latest
          overwrite: true