name: vtk-macos
on: workflow_dispatch
jobs:
  vtk-macos:
    strategy:
      matrix:
        version: [ 9.4.2 ]
    runs-on: macos-13
    steps:
      - name: Compile
        run: |
          export FC=gfortran-13
          brew install glfw glew
          wget -q https://www.vtk.org/files/release/9.4/VTK-${{ matrix.version }}.tar.gz
          tar xf VTK-${{ matrix.version }}.tar.gz && rm VTK-${{ matrix.version }}.tar.gz
          mkdir VTK-build && cd VTK-build
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=../VTK-out ../VTK-${{ matrix.version }}
          cmake --build . --target install --config Release --parallel 4
          cd ../VTK-out
          tar cvzf ../VTK-${{ matrix.version }}-macos.tar.gz ./*
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: VTK-${{ matrix.version }}-macos.tar.gz
          asset_name: VTK-${{ matrix.version }}-macos.tar.gz
          tag: latest
          overwrite: true